# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.CharField(blank=True, max_length=15)),
                ('direction', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='departuredates',
            name='travel_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TravelTimes'),
        ),
    ]
